name: android_build
on:
  push:
    branches:
      - main
      
jobs:
  android_build:
    name: run android build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: android_release
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Create github artifact release # disable this to save storage
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"          
      - name: Upload app bundle artifact
        uses: actions/upload-artifact@v3
        with:
          name: android_release
          path: build/app/outputs/flutter-apk/app-release.apk
